[package]
name = "gestreamer"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
actix-web = "4.6.4"
clap = { version = "4", features = ["derive"] }
clap_derive = "4.6.4"
dbus = { version = "0.9", features = ["futures"] }
dbus-tokio = "0"
gstreamer = "0.25"
gstreamer-app = "0"
shared.workspace = true
thiserror = "2.0.20"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tokio-stream = { version = "0.1", features = ["sync"] }
tracing = "0.1.44"
