// This code was autogenerated with `dbus-codegen-rust -c nonblock --file ./dbus-introspect/display_config.xml --output src/dbus_client/display_config.rs`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::nonblock;

pub trait OrgFreedesktopDBusProperties {
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> nonblock::MethodReply<arg::Variant<Box<dyn arg::RefArg + 'static>>>;
    fn get_all(&self, interface_name: &str) -> nonblock::MethodReply<arg::PropMap>;
    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> nonblock::MethodReply<()>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusProperties
    for nonblock::Proxy<'a, C>
{
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> nonblock::MethodReply<arg::Variant<Box<dyn arg::RefArg + 'static>>> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Get",
            (interface_name, property_name),
        )
        .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>,)| Ok(r.0))
    }

    fn get_all(&self, interface_name: &str) -> nonblock::MethodReply<arg::PropMap> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "GetAll",
            (interface_name,),
        )
        .and_then(|r: (arg::PropMap,)| Ok(r.0))
    }

    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Set",
            (interface_name, property_name, value),
        )
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> nonblock::MethodReply<String>;
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>>
    OrgFreedesktopDBusIntrospectable for nonblock::Proxy<'a, C>
{
    fn introspect(&self) -> nonblock::MethodReply<String> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> nonblock::MethodReply<()>;
    fn get_machine_id(&self) -> nonblock::MethodReply<String>;
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusPeer
    for nonblock::Proxy<'a, C>
{
    fn ping(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> nonblock::MethodReply<String> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait OrgGnomeMutterDisplayConfig {
    fn get_resources(
        &self,
    ) -> nonblock::MethodReply<(
        u32,
        Vec<(
            u32,
            i64,
            i32,
            i32,
            i32,
            i32,
            i32,
            u32,
            Vec<u32>,
            arg::PropMap,
        )>,
        Vec<(
            u32,
            i64,
            i32,
            Vec<u32>,
            String,
            Vec<u32>,
            Vec<u32>,
            arg::PropMap,
        )>,
        Vec<(u32, i64, u32, u32, f64, u32)>,
        i32,
        i32,
    )>;
    fn apply_configuration(
        &self,
        serial: u32,
        persistent: bool,
        crtcs: Vec<(u32, i32, i32, i32, u32, Vec<u32>, arg::PropMap)>,
        outputs: Vec<(u32, arg::PropMap)>,
    ) -> nonblock::MethodReply<()>;
    #[deprecated(note = "true")]
    fn change_backlight(&self, serial: u32, output: u32, value: i32) -> nonblock::MethodReply<i32>;
    fn set_backlight(&self, serial: u32, connector: &str, value: i32) -> nonblock::MethodReply<()>;
    fn get_crtc_gamma(
        &self,
        serial: u32,
        crtc: u32,
    ) -> nonblock::MethodReply<(Vec<u16>, Vec<u16>, Vec<u16>)>;
    fn set_crtc_gamma(
        &self,
        serial: u32,
        crtc: u32,
        red: Vec<u16>,
        green: Vec<u16>,
        blue: Vec<u16>,
    ) -> nonblock::MethodReply<()>;
    fn get_current_state(
        &self,
    ) -> nonblock::MethodReply<(
        u32,
        Vec<(
            (String, String, String, String),
            Vec<(String, i32, i32, f64, f64, Vec<f64>, arg::PropMap)>,
            arg::PropMap,
        )>,
        Vec<(
            i32,
            i32,
            f64,
            u32,
            bool,
            Vec<(String, String, String, String)>,
            arg::PropMap,
        )>,
        arg::PropMap,
    )>;
    fn apply_monitors_config(
        &self,
        serial: u32,
        method: u32,
        logical_monitors: Vec<(i32, i32, f64, u32, bool, Vec<(&str, &str, arg::PropMap)>)>,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<()>;
    fn set_output_ctm(
        &self,
        serial: u32,
        output: u32,
        ctm: (u64, u64, u64, u64, u64, u64, u64, u64, u64),
    ) -> nonblock::MethodReply<()>;
    fn backlight(&self) -> nonblock::MethodReply<(u32, Vec<arg::PropMap>)>;
    fn power_save_mode(&self) -> nonblock::MethodReply<i32>;
    fn set_power_save_mode(&self, value: i32) -> nonblock::MethodReply<()>;
    fn panel_orientation_managed(&self) -> nonblock::MethodReply<bool>;
    fn apply_monitors_config_allowed(&self) -> nonblock::MethodReply<bool>;
    fn night_light_supported(&self) -> nonblock::MethodReply<bool>;
    fn has_external_monitor(&self) -> nonblock::MethodReply<bool>;
}

#[derive(Debug)]
pub struct OrgGnomeMutterDisplayConfigMonitorsChanged {}

impl arg::AppendAll for OrgGnomeMutterDisplayConfigMonitorsChanged {
    fn append(&self, _: &mut arg::IterAppend) {}
}

impl arg::ReadAll for OrgGnomeMutterDisplayConfigMonitorsChanged {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgGnomeMutterDisplayConfigMonitorsChanged {})
    }
}

impl dbus::message::SignalArgs for OrgGnomeMutterDisplayConfigMonitorsChanged {
    const NAME: &'static str = "MonitorsChanged";
    const INTERFACE: &'static str = "org.gnome.Mutter.DisplayConfig";
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>> OrgGnomeMutterDisplayConfig
    for nonblock::Proxy<'a, C>
{
    fn get_resources(
        &self,
    ) -> nonblock::MethodReply<(
        u32,
        Vec<(
            u32,
            i64,
            i32,
            i32,
            i32,
            i32,
            i32,
            u32,
            Vec<u32>,
            arg::PropMap,
        )>,
        Vec<(
            u32,
            i64,
            i32,
            Vec<u32>,
            String,
            Vec<u32>,
            Vec<u32>,
            arg::PropMap,
        )>,
        Vec<(u32, i64, u32, u32, f64, u32)>,
        i32,
        i32,
    )> {
        self.method_call("org.gnome.Mutter.DisplayConfig", "GetResources", ())
    }

    fn apply_configuration(
        &self,
        serial: u32,
        persistent: bool,
        crtcs: Vec<(u32, i32, i32, i32, u32, Vec<u32>, arg::PropMap)>,
        outputs: Vec<(u32, arg::PropMap)>,
    ) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.gnome.Mutter.DisplayConfig",
            "ApplyConfiguration",
            (serial, persistent, crtcs, outputs),
        )
    }

    fn change_backlight(&self, serial: u32, output: u32, value: i32) -> nonblock::MethodReply<i32> {
        self.method_call(
            "org.gnome.Mutter.DisplayConfig",
            "ChangeBacklight",
            (serial, output, value),
        )
        .and_then(|r: (i32,)| Ok(r.0))
    }

    fn set_backlight(&self, serial: u32, connector: &str, value: i32) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.gnome.Mutter.DisplayConfig",
            "SetBacklight",
            (serial, connector, value),
        )
    }

    fn get_crtc_gamma(
        &self,
        serial: u32,
        crtc: u32,
    ) -> nonblock::MethodReply<(Vec<u16>, Vec<u16>, Vec<u16>)> {
        self.method_call(
            "org.gnome.Mutter.DisplayConfig",
            "GetCrtcGamma",
            (serial, crtc),
        )
    }

    fn set_crtc_gamma(
        &self,
        serial: u32,
        crtc: u32,
        red: Vec<u16>,
        green: Vec<u16>,
        blue: Vec<u16>,
    ) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.gnome.Mutter.DisplayConfig",
            "SetCrtcGamma",
            (serial, crtc, red, green, blue),
        )
    }

    fn get_current_state(
        &self,
    ) -> nonblock::MethodReply<(
        u32,
        Vec<(
            (String, String, String, String),
            Vec<(String, i32, i32, f64, f64, Vec<f64>, arg::PropMap)>,
            arg::PropMap,
        )>,
        Vec<(
            i32,
            i32,
            f64,
            u32,
            bool,
            Vec<(String, String, String, String)>,
            arg::PropMap,
        )>,
        arg::PropMap,
    )> {
        self.method_call("org.gnome.Mutter.DisplayConfig", "GetCurrentState", ())
    }

    fn apply_monitors_config(
        &self,
        serial: u32,
        method: u32,
        logical_monitors: Vec<(i32, i32, f64, u32, bool, Vec<(&str, &str, arg::PropMap)>)>,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.gnome.Mutter.DisplayConfig",
            "ApplyMonitorsConfig",
            (serial, method, logical_monitors, properties),
        )
    }

    fn set_output_ctm(
        &self,
        serial: u32,
        output: u32,
        ctm: (u64, u64, u64, u64, u64, u64, u64, u64, u64),
    ) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.gnome.Mutter.DisplayConfig",
            "SetOutputCTM",
            (serial, output, ctm),
        )
    }

    fn backlight(&self) -> nonblock::MethodReply<(u32, Vec<arg::PropMap>)> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.gnome.Mutter.DisplayConfig",
            "Backlight",
        )
    }

    fn power_save_mode(&self) -> nonblock::MethodReply<i32> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.gnome.Mutter.DisplayConfig",
            "PowerSaveMode",
        )
    }

    fn panel_orientation_managed(&self) -> nonblock::MethodReply<bool> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.gnome.Mutter.DisplayConfig",
            "PanelOrientationManaged",
        )
    }

    fn apply_monitors_config_allowed(&self) -> nonblock::MethodReply<bool> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.gnome.Mutter.DisplayConfig",
            "ApplyMonitorsConfigAllowed",
        )
    }

    fn night_light_supported(&self) -> nonblock::MethodReply<bool> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.gnome.Mutter.DisplayConfig",
            "NightLightSupported",
        )
    }

    fn has_external_monitor(&self) -> nonblock::MethodReply<bool> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.gnome.Mutter.DisplayConfig",
            "HasExternalMonitor",
        )
    }

    fn set_power_save_mode(&self, value: i32) -> nonblock::MethodReply<()> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::set(
            self,
            "org.gnome.Mutter.DisplayConfig",
            "PowerSaveMode",
            value,
        )
    }
}
