// This code was autogenerated with `dbus-codegen-rust -c nonblock --file ./dbus-introspect/screencast_session.xml --output src/dbus_client/screencast_session.rs`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::nonblock;

pub trait OrgFreedesktopDBusProperties {
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> nonblock::MethodReply<arg::Variant<Box<dyn arg::RefArg + 'static>>>;
    fn get_all(&self, interface_name: &str) -> nonblock::MethodReply<arg::PropMap>;
    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> nonblock::MethodReply<()>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusProperties
    for nonblock::Proxy<'a, C>
{
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> nonblock::MethodReply<arg::Variant<Box<dyn arg::RefArg + 'static>>> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Get",
            (interface_name, property_name),
        )
        .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>,)| Ok(r.0))
    }

    fn get_all(&self, interface_name: &str) -> nonblock::MethodReply<arg::PropMap> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "GetAll",
            (interface_name,),
        )
        .and_then(|r: (arg::PropMap,)| Ok(r.0))
    }

    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Set",
            (interface_name, property_name, value),
        )
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> nonblock::MethodReply<String>;
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>>
    OrgFreedesktopDBusIntrospectable for nonblock::Proxy<'a, C>
{
    fn introspect(&self) -> nonblock::MethodReply<String> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> nonblock::MethodReply<()>;
    fn get_machine_id(&self) -> nonblock::MethodReply<String>;
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusPeer
    for nonblock::Proxy<'a, C>
{
    fn ping(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> nonblock::MethodReply<String> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait OrgGnomeMutterScreenCastSession {
    fn start(&self) -> nonblock::MethodReply<()>;
    fn stop(&self) -> nonblock::MethodReply<()>;
    fn record_monitor(
        &self,
        connector: &str,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<dbus::Path<'static>>;
    fn record_window(&self, properties: arg::PropMap)
    -> nonblock::MethodReply<dbus::Path<'static>>;
    fn record_area(
        &self,
        x_: i32,
        y_: i32,
        width: i32,
        height: i32,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<dbus::Path<'static>>;
    fn record_virtual(
        &self,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<dbus::Path<'static>>;
}

#[derive(Debug)]
pub struct OrgGnomeMutterScreenCastSessionClosed {}

impl arg::AppendAll for OrgGnomeMutterScreenCastSessionClosed {
    fn append(&self, _: &mut arg::IterAppend) {}
}

impl arg::ReadAll for OrgGnomeMutterScreenCastSessionClosed {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgGnomeMutterScreenCastSessionClosed {})
    }
}

impl dbus::message::SignalArgs for OrgGnomeMutterScreenCastSessionClosed {
    const NAME: &'static str = "Closed";
    const INTERFACE: &'static str = "org.gnome.Mutter.ScreenCast.Session";
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>>
    OrgGnomeMutterScreenCastSession for nonblock::Proxy<'a, C>
{
    fn start(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.gnome.Mutter.ScreenCast.Session", "Start", ())
    }

    fn stop(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.gnome.Mutter.ScreenCast.Session", "Stop", ())
    }

    fn record_monitor(
        &self,
        connector: &str,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<dbus::Path<'static>> {
        self.method_call(
            "org.gnome.Mutter.ScreenCast.Session",
            "RecordMonitor",
            (connector, properties),
        )
        .and_then(|r: (dbus::Path<'static>,)| Ok(r.0))
    }

    fn record_window(
        &self,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<dbus::Path<'static>> {
        self.method_call(
            "org.gnome.Mutter.ScreenCast.Session",
            "RecordWindow",
            (properties,),
        )
        .and_then(|r: (dbus::Path<'static>,)| Ok(r.0))
    }

    fn record_area(
        &self,
        x_: i32,
        y_: i32,
        width: i32,
        height: i32,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<dbus::Path<'static>> {
        self.method_call(
            "org.gnome.Mutter.ScreenCast.Session",
            "RecordArea",
            (x_, y_, width, height, properties),
        )
        .and_then(|r: (dbus::Path<'static>,)| Ok(r.0))
    }

    fn record_virtual(
        &self,
        properties: arg::PropMap,
    ) -> nonblock::MethodReply<dbus::Path<'static>> {
        self.method_call(
            "org.gnome.Mutter.ScreenCast.Session",
            "RecordVirtual",
            (properties,),
        )
        .and_then(|r: (dbus::Path<'static>,)| Ok(r.0))
    }
}
